

# APPLICATION BROWSER
browser=chrome
# APPLICATION URL
url=https://www.demoblaze.com/
# APPLICATION USERNAME AND PASSWORD
username=Nandinirajan19
 password=651919

name=NandiniRajan
country=India
city=Chennai
creditCard= 8925419654
month=26
year=2026